### ISSUE TITLE
Rest api vs native mobile skd

### ISSUE THREAD

**Issue by kherel** [GAM3RG33K/flutter_authorize_net_client#2]
- How do you think would it have any problems to use Authorize REST API and not native mobile SDK? 
- Is it possible to use apple pay and google pay?

**Comment by GAM3RG33K** [comment]
- Using the native SDK requires coding on native side of the projects, in which iOS is not possible for me, I don't know swift or Objective C
- It is possible to integrate apple pay & google pay using rest api, refer to this: https://developer.authorize.net/api/reference/index.html#mobile-in-app-transactions

As you can see in the ReadMe file, this plugin only supports very basic operations now, I am planning to add more operations one by one. But before that I want to cover the current ones in test cases for safety.

If you want to contribute with native sdk integration, we can make a different branch & release it as a separate plugin.

**Comment by kherel** [comment]
Do you know about publishing in google play and appstore. Would it be okay for them? Using rest api in the app?
